import { Geist, Geist_Mono } from "next/font/google";
import ThemeProvider from "./ThemeProvider";
import "./globals.css";

import Header from "@/components/header";
import Footer from "@/components/footer";
import StorProvaider from "./storProvaider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
      >
        <ThemeProvider>
          <Header/>
          
          <main className="flex-grow min-h-screen">
            <StorProvaider>
            {children}
            </StorProvaider>
          </main>


        <Footer/>
        </ThemeProvider>
        
      </body>
    </html>
  );
}
